-- ============================================
-- DADOS DO BANCO LOCAL - Pirata Pizzaria
-- Gerado em: 01/01/2026, 22:14:32
-- Execute no phpMyAdmin APÓS criar as tabelas
-- ============================================

-- USUÁRIOS
DELETE FROM users WHERE id NOT IN ('cm5bn4admin001');
INSERT INTO users (id, name, email, password, role, createdAt, updatedAt) VALUES (
  'cmjrllx260000febk80hkkfz1',
  'Administrador',
  'admin@piratapizzaria.com.br',
  '$2b$10$xcJvsMOdqwdkg5eEjXMEae8Q5EnM62bAY0gtdEKYCfBqQRie.wi.S',
  'ADMIN',
  '2025-12-29 20:15:55',
  '2025-12-31 17:27:48'
) ON DUPLICATE KEY UPDATE name = VALUES(name), password = VALUES(password), role = VALUES(role);

INSERT INTO users (id, name, email, password, role, createdAt, updatedAt) VALUES (
  'cmjrr76nl0000q1xwmqhft06b',
  'Rebeca',
  'rebeca@piratapizzaria.com.br',
  '$2b$10$Iyy8P.OWKapXuVPif6XN9.cLEGA9e3sCx0T6YFrPGbxc47Crtp.ee',
  'MANAGER',
  '2025-12-29 22:52:26',
  '2025-12-29 22:52:26'
) ON DUPLICATE KEY UPDATE name = VALUES(name), password = VALUES(password), role = VALUES(role);

INSERT INTO users (id, name, email, password, role, createdAt, updatedAt) VALUES (
  'cmjryj44c009gjk7vvk8qssbi',
  'Henry',
  'henry@piratapizzaria.com.br',
  '$2b$10$Qh0WoYQMNd0aeZidlZZPMejMHbvCLsIgLfEZEp5n6eRwYernqYcO.',
  'MANAGER',
  '2025-12-30 02:17:39',
  '2025-12-30 02:17:39'
) ON DUPLICATE KEY UPDATE name = VALUES(name), password = VALUES(password), role = VALUES(role);


-- FUNCIONÁRIOS
INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'andressa',
  'Andressa',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  true,
  'SHIFT',
  55,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  65,
  85,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'bianca',
  'Bianca',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  true,
  'SHIFT',
  55,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  65,
  85,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'caio',
  'Caio',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  true,
  'SHIFT',
  50,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  60,
  80,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'catia',
  'Catia',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  true,
  'SHIFT',
  60,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  70,
  90,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'cleber',
  'Cleber',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  80,
  100,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'cleia',
  'Cleia',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  true,
  'SHIFT',
  60,
  '11:00',
  '17:00',
  false,
  'SHIFT',
  0,
  0,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'duda',
  'Duda',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  55,
  75,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'duda-loira',
  'Duda Loira',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  55,
  75,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'felipe',
  'Felipe',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  75,
  95,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'gil',
  'Gil',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  80,
  100,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'henry',
  'Henry',
  'Funcionário',
  3000,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  true,
  'MONTH',
  2000,
  '11:00',
  '17:00',
  false,
  'SHIFT',
  0,
  0,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'isaias',
  'Isaias',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  true,
  'HOUR',
  10,
  '11:00',
  '17:00',
  true,
  'HOUR',
  12,
  15,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'kaio',
  'Kaio',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  true,
  'SHIFT',
  50,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  60,
  80,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'lais',
  'Lais',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  true,
  'SHIFT',
  55,
  '11:00',
  '17:00',
  false,
  'SHIFT',
  0,
  0,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'lara',
  'Lara',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  55,
  75,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'ligia',
  'Ligia',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  65,
  85,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'marina',
  'Marina',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  60,
  80,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'miguel',
  'Miguel',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  65,
  85,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'miqueias-moto',
  'Miqueias Moto',
  'Funcionário',
  0,
  NULL,
  NULL,
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  50,
  70,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'mudinho',
  'Mudinho',
  'Funcionário',
  0,
  NULL,
  NULL,
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  60,
  80,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'nayara',
  'Nayara',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  65,
  85,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'rebeca',
  'Rebeca',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'HOUR',
  12,
  15,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'silva',
  'Silva',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  70,
  90,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'stephanie',
  'Stephanie',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  60,
  80,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'valdeir-moto',
  'Valdeir Moto',
  'Funcionário',
  0,
  NULL,
  NULL,
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  50,
  70,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'vinicius',
  'Vinicius',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  70,
  90,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);

INSERT INTO employees (id, name, role, salary, phone, document, hireDate, active,
  worksLunch, lunchPaymentType, lunchValue, lunchStartTime, lunchEndTime,
  worksDinner, dinnerPaymentType, dinnerWeekdayValue, dinnerWeekendValue, dinnerStartTime, dinnerEndTime,
  createdAt, updatedAt) VALUES (
  'vitoria',
  'Vitoria',
  'Funcionário',
  0,
  '',
  '',
  '2025-12-29 20:15:55',
  true,
  false,
  'SHIFT',
  0,
  '11:00',
  '17:00',
  true,
  'SHIFT',
  55,
  75,
  '17:00',
  '00:00',
  '2025-12-29 20:15:55',
  '2025-12-30 00:07:15'
) ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  worksLunch = VALUES(worksLunch),
  lunchPaymentType = VALUES(lunchPaymentType),
  lunchValue = VALUES(lunchValue),
  worksDinner = VALUES(worksDinner),
  dinnerPaymentType = VALUES(dinnerPaymentType),
  dinnerWeekdayValue = VALUES(dinnerWeekdayValue),
  dinnerWeekendValue = VALUES(dinnerWeekendValue);


-- CONFIGURAÇÕES DE TURNO
INSERT INTO shift_configs (id, name, description, value, createdAt, updatedAt) VALUES (
  'cmjrllx2a0001febkgk5k73ol',
  'lunch',
  'Almoço (todos os dias)',
  50,
  '2025-12-29 20:15:55',
  '2025-12-29 20:15:55'
) ON DUPLICATE KEY UPDATE description = VALUES(description), value = VALUES(value);

INSERT INTO shift_configs (id, name, description, value, createdAt, updatedAt) VALUES (
  'cmjrllx2b0002febkckek00m5',
  'dinner_weekday',
  'Jantar (Segunda a Sexta)',
  60,
  '2025-12-29 20:15:55',
  '2025-12-29 20:15:55'
) ON DUPLICATE KEY UPDATE description = VALUES(description), value = VALUES(value);

INSERT INTO shift_configs (id, name, description, value, createdAt, updatedAt) VALUES (
  'cmjrllx2c0003febk3zpyhmll',
  'dinner_weekend',
  'Jantar (Sábado e Domingo)',
  80,
  '2025-12-29 20:15:55',
  '2025-12-29 20:15:55'
) ON DUPLICATE KEY UPDATE description = VALUES(description), value = VALUES(value);


-- ADIANTAMENTOS
INSERT INTO advances (id, employeeId, amount, requestDate, paymentDate, status, notes, createdAt, updatedAt) VALUES (
  'cmjru55ok001rq1xwgiwg0vuv',
  'caio',
  20,
  '2025-12-29 00:00:00',
  '2025-12-30 01:33:06',
  'DISCOUNTED',
  NULL,
  '2025-12-30 00:14:50',
  '2025-12-30 01:33:19'
) ON DUPLICATE KEY UPDATE status = VALUES(status), paymentDate = VALUES(paymentDate);

INSERT INTO advances (id, employeeId, amount, requestDate, paymentDate, status, notes, createdAt, updatedAt) VALUES (
  'cmjru5ugi001tq1xw476pq4rh',
  'cleber',
  50,
  '2025-12-29 00:00:00',
  '2025-12-30 01:33:06',
  'DISCOUNTED',
  NULL,
  '2025-12-30 00:15:22',
  '2025-12-30 01:33:19'
) ON DUPLICATE KEY UPDATE status = VALUES(status), paymentDate = VALUES(paymentDate);

INSERT INTO advances (id, employeeId, amount, requestDate, paymentDate, status, notes, createdAt, updatedAt) VALUES (
  'cmjru7hry001vq1xw5qu22vrz',
  'cleia',
  20,
  '2025-12-29 00:00:00',
  '2025-12-30 01:33:06',
  'DISCOUNTED',
  NULL,
  '2025-12-30 00:16:39',
  '2025-12-30 01:33:19'
) ON DUPLICATE KEY UPDATE status = VALUES(status), paymentDate = VALUES(paymentDate);

INSERT INTO advances (id, employeeId, amount, requestDate, paymentDate, status, notes, createdAt, updatedAt) VALUES (
  'cmjrwyvpp0071jk7vqgf35g7a',
  'cleber',
  100,
  '2025-12-29 00:00:00',
  '2025-12-30 01:34:02',
  'DISCOUNTED',
  NULL,
  '2025-12-30 01:33:56',
  '2025-12-30 01:34:15'
) ON DUPLICATE KEY UPDATE status = VALUES(status), paymentDate = VALUES(paymentDate);

INSERT INTO advances (id, employeeId, amount, requestDate, paymentDate, status, notes, createdAt, updatedAt) VALUES (
  'cmjry3os4007vjk7vhe5htkiy',
  'isaias',
  100,
  '2025-12-29 00:00:00',
  '2025-12-30 02:05:47',
  'DISCOUNTED',
  NULL,
  '2025-12-30 02:05:40',
  '2025-12-30 02:06:08'
) ON DUPLICATE KEY UPDATE status = VALUES(status), paymentDate = VALUES(paymentDate);

INSERT INTO advances (id, employeeId, amount, requestDate, paymentDate, status, notes, createdAt, updatedAt) VALUES (
  'cmjstqcas0010i3tfbxaf8i80',
  'andressa',
  100,
  '2025-12-29 00:00:00',
  '2025-12-30 16:51:10',
  'DISCOUNTED',
  NULL,
  '2025-12-30 16:51:05',
  '2025-12-30 16:51:24'
) ON DUPLICATE KEY UPDATE status = VALUES(status), paymentDate = VALUES(paymentDate);

INSERT INTO advances (id, employeeId, amount, requestDate, paymentDate, status, notes, createdAt, updatedAt) VALUES (
  'cmjtc9p3c000t8fw69xfz85lw',
  'cleia',
  80,
  '2025-12-30 00:00:00',
  '2025-12-31 01:30:07',
  'DISCOUNTED',
  NULL,
  '2025-12-31 01:30:01',
  '2026-01-02 00:52:38'
) ON DUPLICATE KEY UPDATE status = VALUES(status), paymentDate = VALUES(paymentDate);


-- DESPESAS
INSERT INTO expenses (id, category, description, amount, date, notes, createdAt, updatedAt) VALUES (
  'cmjrtt6dy001lq1xw7yuflgv9',
  'INGREDIENTS',
  'Tenda',
  408,
  '2025-12-30 00:00:00',
  NULL,
  '2025-12-30 00:05:31',
  '2025-12-30 00:05:31'
) ON DUPLICATE KEY UPDATE description = VALUES(description), amount = VALUES(amount);

INSERT INTO expenses (id, category, description, amount, date, notes, createdAt, updatedAt) VALUES (
  'cmjrtui1g001mq1xwicnk0bd6',
  'INGREDIENTS',
  'Mercadão Atacadista',
  88.56,
  '2025-12-30 00:00:00',
  NULL,
  '2025-12-30 00:06:33',
  '2025-12-30 00:06:33'
) ON DUPLICATE KEY UPDATE description = VALUES(description), amount = VALUES(amount);

INSERT INTO expenses (id, category, description, amount, date, notes, createdAt, updatedAt) VALUES (
  'cmjrtx51l001oq1xwru6ppv6r',
  'INGREDIENTS',
  'Krill',
  35.97,
  '2025-12-30 00:00:00',
  NULL,
  '2025-12-30 00:08:36',
  '2025-12-30 00:08:36'
) ON DUPLICATE KEY UPDATE description = VALUES(description), amount = VALUES(amount);

INSERT INTO expenses (id, category, description, amount, date, notes, createdAt, updatedAt) VALUES (
  'cmjru012x001pq1xwucfodhbj',
  'INGREDIENTS',
  'Krill',
  38.95,
  '2025-12-29 00:00:00',
  NULL,
  '2025-12-30 00:10:51',
  '2025-12-30 00:10:51'
) ON DUPLICATE KEY UPDATE description = VALUES(description), amount = VALUES(amount);


-- ============================================
-- FIM DA IMPORTAÇÃO
-- Total de funcionários: 27
-- Total de adiantamentos: 7
-- Total de despesas: 4
-- Total de receitas: 0
-- ============================================
